### ISSUE TITLE
Unable to rotate a shape along a circle 

### ISSUE THREAD

**Issue by abreitenfeld** [sureskumar/Looper#12]
Hey there, I try to recreate one of your example (rotate linear) where you distribute a dot along a circle. I tried to play around with the settings but without any luck. Maybe I need to translate the pivot of the dot to a new origin. Can you give some help on this? I use version 2.4 of Looper.

**Comment by sureskumar** [comment]
Hey, its a simple trick. Make a rectangle with no border and fill. Place the circle that you would like to rotate on one corner of the rectangle (see pic attached). Group the rectangle and circle . Then apply Looper filter on the group. Basically we use this trick to move the anchor point during rotation. Hope this helps! Cheers, Sures

![screen shot 2017-06-08 at 10 01 01 am](https://user-images.githubusercontent.com/1582440/26912376-7da125be-4c31-11e7-8c73-333d2815ea7c.png)

**Comment by bzx** [comment]
Since this is one of the first shapes that a new Looper user will try to achieve (including me), it would be nice if you could add this as the main tutorial example... I spent too much time figuring this out by myself.. Thanks!
