### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mischugo** [sureskumar/Looper#14]
This plug in is awesome!!!! Thanks

Whats about the possibility to edit the illustration again, to do some corrections?
Selecting the layer -> open Looper -> create new / edit ...

Best

Mischu

**Comment by sureskumar** [comment]
Great feedback. will add it in the future versions. Cheers!

**Comment by mischugo** [comment]
Sound good :-)


Sures Kumar <notifications@github.com> schrieb am Mi. 21. Juni 2017 um
14:31:
