### ISSUE TITLE
Plugin don't allow to enter a number in a field

### ISSUE THREAD

**Issue by osenvosem** [sureskumar/Looper#16]
The setting window lose it's focus after I enter the first number or delete a number.

![ulwx6ou9oz](https://user-images.githubusercontent.com/6762673/29259024-85e366ea-80c7-11e7-87b6-db3d309e8cf8.gif)

The plugin also make unnecessary re-renders. If, for instance, you have `1` in the "Number of copies fields" and press down key, nothing is supposed to change but the plugin re-renders anyway.

**Comment by sureskumar** [comment]
Super valuable feedback. will fix this soon!

**Comment by RomainSauvaire** [comment]
I have exactly the same problem. Are you working on this already ?

**Comment by goldade** [comment]
Hi Romain,

no I don't, but I hope someoneelse does. 


Von meinem iPhone gesendet

**Comment by sureskumar** [comment]
I will work on this. Just not been getting time to pick this up. Cheers!

**Comment by sureskumar** [comment]
Hey guys, This issue is now fixed in the latest version of the Looper Plugin. Please try the plugin and let me know if it works. Cheers!
