### ISSUE TITLE
Enable sub-pixel positioning

### ISSUE THREAD

**Issue by jacobclarke92** [sureskumar/Looper#17]
I know it's probably frowned upon to have anything except .5 pixels in sketch but it would be useful to allow decimal numbers for the inputs.

I was trying to horizontally align a bunch of lines to fit in a space where the exact spacing I needed was 7.5, just seemed like a simple request to implement.

P.S. I love the creative possibilities of your plugin!

**Comment by sureskumar** [comment]
Cool feature idea, will work on this soon. Cheers!

**Comment by sureskumar** [comment]
Hi Jacob, This issue is now fixed in the latest version of the Looper Plugin. Cheers!
