### ISSUE TITLE
Not working in Sketch 48

### ISSUE THREAD

**Issue by jamesatthelift** [sureskumar/Looper#18]
<img width="1440" alt="looper-bug-1" src="https://user-images.githubusercontent.com/669102/35409104-1c9e78ca-01c6-11e8-9b5c-ff5f897f88d1.png">
<img width="1440" alt="looper-bug-2" src="https://user-images.githubusercontent.com/669102/35409103-1c805e26-01c6-11e8-8b4c-557323449705.png">
<img width="1440" alt="looper-bug-3" src="https://user-images.githubusercontent.com/669102/35409102-1c6225b4-01c6-11e8-9949-a8eea45f420c.png">

The plugin no longer works for me. I'm not able to see previews while configuring. After applying a loop, the layer group is flattened into a single layer that cannot be selected. If I hit 'Undo', the layer group folder displays (along with the layer copies), but the effect did not compose on the artboard (all layers are stacked on each other).

**Comment by davemoz** [comment]
Doesn't work in recently released v49 either.

**Comment by sureskumar** [comment]
Hey Dave, I am not able to replicate this :( Can you try removing other plugins and give it a try to just make sure its not bec of an conflict of some sorts? Cheers!

**Comment by hazelmotes** [comment]
I have the same issue and have no other plugins installed. Deleted and reinstalled Looper but still have the same results — no preview while using the plugin and the layer group cannot be selected.
