### ISSUE TITLE
Fields don't allow for multi key entry

### ISSUE THREAD

**Issue by naher94** [sureskumar/Looper#21]
after every key press in a field it redirects the active button to done making it painful to update more that one digital without reselecting the field

**Comment by sureskumar** [comment]
Thanks for reporting Naher. I will fix this soon. Cheers!

**Comment by naher94** [comment]
Thanks for the plugin!

**Comment by sureskumar** [comment]
Hi Naher, This issue is now fixed in the latest version of the Looper Plugin. Cheers!
