### ISSUE TITLE
Offset amounts only respect integer values.

### ISSUE THREAD

**Issue by HasanEdain** [sureskumar/Looper#22]
I have a need for offset amounts in sub integer (floating point) ranges.
I would like to take an rectangle that is 8 pixels wide and 4.63 pixels high, and make a grid of them such that the edges overlap, hiding each other (rectangular graph paper).

When I enter the values (selecting the field after each key stroke), only the integer portion of the input is respected in the render.

**Comment by sureskumar** [comment]
Hi HasanEdain, Thanks for letting me know. This issue is now fixed in the latest version of the Looper Plugin. Cheers!
