### ISSUE TITLE
Feature request: Duplicate along wave form paths

### ISSUE THREAD

**Issue by mikeprecious** [sureskumar/Looper#23]
Feature request:

Be able to duplicate a vector object along a vector wave shape form. Use case: I'd like to create an interesting visual of circular user thumbnail images where there is a sense of front to back depth of field, it would be neat to create a wave form like shape for the shapes to be duplicated along. 

Thanks!

**Comment by sureskumar** [comment]
Hey Mike, I can imagine some interesting ideas. But I am not sure I am understanding your FR. Can you point me to some sample images of some sorts?
