### ISSUE TITLE
"Number of copies" behaves differently than Sketch's native Rotate Copies feature

### ISSUE THREAD

**Issue by warpling** [sureskumar/Looper#25]
Sketch's "Rotate Copies" feature asks for a "Number of copies" and then clarifies "You will have (n+1) layers in total". This is helpful since the number of copies can be confusing when someone is just trying to have a certain number of objects. Looper's "Number of copies" is the number of end objects (n+1). This can be problematic for someone new to the plugin who'd expect it to behave like Sketch's native feature.

Solution: Change the copy to reflect that this is the final number of objects, or add subtext to clarify the actual number of objects like the native feature does.

Unrelated: It might be beneficial to set the starting default to something smaller than 50. When I first tried the plugin it was very sluggish and seeing an uncountable 50 copies missed a teachable moment to show me that the number of copies entered is the final number of objects! :)

**Comment by warpling** [comment]
My pleasure! Thanks for the great plugin!

**Comment by sureskumar** [comment]
Have added the sub text as suggested. Check out the latest version here: https://github.com/sureskumar/Looper/releases/download/v3.0/Looper.sketchplugin.zip Cheers!

**Comment by warpling** [comment]
Mine is just showing an asterisk?
![screen shot 2018-12-27 at 9 54 48 am](https://user-images.githubusercontent.com/220240/50489611-f8b2e300-0a08-11e9-91e0-e0597cb77e2d.png)

**Comment by sureskumar** [comment]
Thats the sub text clarifying that the output will have this many number of total layers.

**Comment by warpling** [comment]
In that case since the title of the input itself doesn't have an asterisk it would make sense to leave out the asterisk but for even more explicit clarification it would make sense to say "You will have 7 layers total". I feel like even adding "Total" to the title ("Total number of copies") would really make things unambiguous. This doesn't parallel what Sketch does but I think the Rotate Copies tool in Sketch is pretty unintuitive—not sure if you agree. :)
