### ISSUE TITLE
More scaling options

### ISSUE THREAD

**Issue by jounih** [sureskumar/Looper#27]
Thanks for your work!

For scaling, it would be super useful to be able to choose either horizontal or vertical scaling, or both.

Also, to be able to define anchoring/reference point for the scaled copies (like in sketch with t/m/b) - https://sketchtalk.io/discussion/1057/sketch-3-3-beta-new-features-illustrated

It would also be nice to optionally add some amount of randomness to the absolute pixel or percentage change of scaling!

**Comment by sureskumar** [comment]
Thanks for the feature ideas Jouni. Will implement in the next version! Cheers!
