### ISSUE TITLE
Looper doesn't work on Sketch 52.2

### ISSUE THREAD

**Issue by MatteoPadova** [sureskumar/Looper#28]
Unfortunately as the title say, looper just doesn't generate any loop on the 52.2 version of sketch.
Anyone having this issue?

**Comment by sureskumar** [comment]
Hey, Thanks for informing. When I tried to replicate the error, It did not work the first time I installed the plugin. But started working from the second try. I am not able to replicate the first time error again. Can you please try using the plugin again and let me know if it works? Cheers!

**Comment by MatteoPadova** [comment]
Yes, after uninstalled and installed again, the first time it failed, the second it worked. 
I still feel that is a bug that maybe should be fixed but at least now it works! 
Thank you!

**Comment by sureskumar** [comment]
Thanks for checking. I will look into it this weekend. Cheers!

**Comment by Praneeth-Pike** [comment]
@sureskumar I understand you're looking into it, but just trying to mention that I'm running into the same issue as well. However, it doesn't work for me even after reinstalling. Not even the second/ third time.

**Comment by sureskumar** [comment]
Hey Praneeth, Please make sure you have installed the latest version of the plugin and try again. It should work now. Cheers!
