### ISSUE TITLE
Feature Request: scale only in x or y direction

### ISSUE THREAD

**Issue by jayliu50** [sureskumar/Looper#31]
It would be fantastic if you could choose to only Scale in the X or Y direction!

This would be great for making bar charts for example.

**Comment by sureskumar** [comment]
Great suggestion Jay! Will implement in the next version. Cheers!

**Comment by jayliu50** [comment]
Thank you so much! Awesome work!

**Comment by sureskumar** [comment]
Hey Jay, have added the feature as suggested. Check out the latest version here: https://github.com/sureskumar/Looper/releases/download/v3.0/Looper.sketchplugin.zip Cheers!
