### ISSUE TITLE
Improve object naming and grouping

### ISSUE THREAD

**Issue by alexkaessner** [sureskumar/Looper#33]
Is there a reason for this naming and grouping of the object copies?

<img width="300" alt="screenshot" src="https://user-images.githubusercontent.com/6615076/49818056-17ab4700-fd72-11e8-8370-5277fa4f8e30.png">

Why is it adding this strange and complicated number at the end (sometimes also for the copies)? And why does it create 2 groups?

I would suggest something like this:

📁 Looper Group
⎿ 🖊 My Name_1
⎿ 🖊 My Name_2
⎿ 🖊 My Name_3
⎿ 🖊 My Name_4
🖊 My Name_original

**Comment by alexkaessner** [comment]
**It makes sense to keep the original and grouping the generated files - no question!**

As the original file isn't even inside one of the groups I thought it's quite useless to create the "My Name Group" inside the "Looper_Group". That's why I basically suggested to only use one group. The naming of the layers is just personal preference at this point, as I love structured layer names. 😉
I would at least move the original layer into the Looper_Group, if you want to keep the grouping.

**Comment by sureskumar** [comment]
Hey Alexander, have cleaned up the naming as you suggested. Check out the latest version here: https://github.com/sureskumar/Looper/releases/download/v3.0/Looper.sketchplugin.zip Cheers!
