### ISSUE TITLE
Cancel button loops while Done button cancels

### ISSUE THREAD

**Issue by namanmaheshwari97** [sureskumar/Looper#36]
Using Sketch 52.6 and the 'Cancel' button loops my objects while the 'Done' button cancels the looping process.

**Comment by sureskumar** [comment]
Hey Naman, thanks for taking the time to contribute. 
I dont understand the issue here, can you explain a bit more in detail please?

**Comment by namanmaheshwari97** [comment]
I had this weird issue: 
- When I set the looping properties for my object and pressed the Done button, it wouldn't loop.
- When I set the looping properties for my object and pressed the Cancel button, it would loop.

It seems to work correctly now(!!)
I believe you can remove the PR.
