### ISSUE TITLE
Looper doesn't work on Sketch 55+

### ISSUE THREAD

**Issue by ivancucer** [sureskumar/Looper#38]
@sureskumar is it possible to fix one so the plugin can work again on Sketch 55+ ?

Thanks in advance!

Best!
Ivan

**Comment by renarsvilnis** [comment]
Had the same issue when installing trough sketchpacks.

Debug the plugin by running: 
`tail -f ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Log.log`
and trying to do a loop, noticed an issue something like "looper manifest.json not found", followed the path and noticed had 2 plugins installed, deleted both and installed fresh from sketch packs and now it is working.

**Comment by qalqi** [comment]
+1

**Comment by cukabeka** [comment]
Hi, I have the same issue und tried using the terminal command. I end up with these 2 lines (when I install + run it first):

```
Could not read image data at /Users/myname/Downloads/Looper.sketchplugin/Contents/Resources/https:/github.com/sureskumar/Looper/raw/master/assets/logo.png
Could not read image data at /Users/myname/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Looper.sketchplugin/Contents/Resources/https:/github.com/sureskumar/Looper/raw/master/assets/logo.png
```
Now I have no idea what to do. Obviously the plugin references somehow to github, but how could I fix this?
