### ISSUE TITLE
Grid scale in direction not wokring as expected

### ISSUE THREAD

**Issue by renarsvilnis** [sureskumar/Looper#39]
Hi,

noticed when I wanted to make a "circle" into the grid the size reduces going vertically that the scale doesn't work as expected as shown in the video.

**Update:**
Also noticed when reducing the size of the circles they are anchored by the top-left corner when something like middle would be wanted

Video issue: https://youtu.be/TpWDfii6VCg

**Comment by sureskumar** [comment]
Hi, Sorry for the delay in responding. I see that you have locked the width (W) and height (H) of your circle. Please unlock it to make sure Looper can scale X and Y individually. Cheers!
