### ISSUE TITLE
Loop button not displayed on 13 inches screen macbook

### ISSUE THREAD

**Issue by HansonChan** [sureskumar/Looper#4]
The  height:766  of panel is not suitable for small screen.

```
url: this.pluginSketch + "/panel/table.html",
      width: 612,
      height: 766,
```

**Comment by sureskumar** [comment]
Thanks for pointing out. Will fix this now.

**Comment by sureskumar** [comment]
Fixed.

**Comment by sureskumar** [comment]
Hey, did a UI refresh and also have added preview mode. Please give it a try and let me know what you think. Cheers!
