### ISSUE TITLE
Panel's Css loading slow

### ISSUE THREAD

**Issue by Jax0rz** [sureskumar/Looper#6]
Please make the panel's css loading faster.
![1](https://cloud.githubusercontent.com/assets/7557357/25552971/2316c3b8-2cda-11e7-8983-5cc4b5941bab.gif)

**Comment by sureskumar** [comment]
Hey, Thanks for the feedback. Have fixed this and also have introduced a preview mode. Please give it a try and let me know what you think. Cheers!
