### ISSUE TITLE
Two thoughts

### ISSUE THREAD

**Issue by YonatanKof** [sureskumar/Looper#8]
**Great plug!**
Here are two thoughts: 
* Please add the ability to increase/decrease numbers in inputs by using the up/down arrow buttons + shift for incremental changes 
* every `cnd+l` leads to a Looper action, but sometimes I'm just checking things out. Please add a `cancel` button so the user won't have to delete the created Looper_Group and show the original object for every such experiment

Best wishes,
Yonatan.

**Comment by sureskumar** [comment]
Great ideas Yonatan. Will implement them very soon!

**Comment by sureskumar** [comment]
Hey, have implemented the increase/decrease numbers using arrow keys in text boxes. Thanks for the suggestion again.

**Comment by sureskumar** [comment]
Thanks agian for the suggestions Yonatan. Both are implemented now. Please check when free. Cheers!

**Comment by YonatanKof** [comment]
Sweet...
Unfortunately, the behavior is unstable. The `cancel` btn appears only after you change the default `rotation` option  + most unfortunate of all,  it doesn't really cancel the operation :-(
For your consideration.

Best regards,
Yonatan.

**Comment by sureskumar** [comment]
Sorry to hear that. Did you try the latest version: https://github.com/sureskumar/Looper/archive/master.zip

**Comment by YonatanKof** [comment]
Fixed! You rock!
Thanks a million :-)

**Comment by sureskumar** [comment]
Glad you liked it. Good day!
